apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp1
  namespace: javaapp
  labels:
    app: javaapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp1
  template:
    metadata:
      labels:
        app: javaapp1
    spec:
      containers:
      - name: myapp
        image: nanajanashia/argocd-app:1.2
        ports:
        - containerPort: 8080
