apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: javaapp
spec:
  type: NodePort
  ports:
  - name: http
    port: 5000
    targetPort: 9000
    protocol: TCP
  selector:
    app: javaapp1
