apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: javaapp
  labels:
    app: javaapp1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: javaapp1
  template:
    metadata:
      labels:
        app: javaapp1
    spec:
      containers:
      - name: javaapp1
        image: 969921119504.dkr.ecr.us-east-1.amazonaws.com/javaapp
        ports:
        - containerPort: 8000
      imagePullSecrets:
      - name: aws-ecr-credentials
